Repository official-Trippy/trippy-front, pull requests merged in 2024-07, with the labels that each got.

#40 [feat] 로그인 로직 분리 및 추가 작업 #31
  public/DefaultBackground.svg
  public/DefaultProfile.svg
  public/instagram.svg
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/privacy/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/Privacy.tsx
  src/components/auth/ServiceInfo.tsx
  src/components/auth/SignUpForm.tsx
  src/components/blogSignUp/BlogRegisterFirst.tsx
  src/components/blogSignUp/BlogRegisterSecond.tsx
  src/components/profile/MyBadge.tsx
  src/components/profile/MyBookmark.tsx
  src/components/profile/MyOotd.tsx
  src/components/profile/MyTicket.tsx
  src/components/profile/UserInformation.tsx
  src/components/shared/footer/Footer.tsx
  src/components/userInfo/userModal.tsx
  src/constants/blogPreference.ts
  src/styles/globals.css
  src/types/auth.ts
Labels: fix, design, chore, feat

#46 design: 내정보수정페이지 레이아웃(미완)
  src/app/editProfile/page.tsx
  src/components/profile/EditInfo.tsx
  src/components/profile/UserInformation.tsx
Labels: design

#50 [feat] ootd api & 날씨조회 api
  package-lock.json
  package.json
  public/OotdDefault.png
  public/dropdown.svg
  public/icon_down.png
  src/app/write/page.tsx
  src/components/ootd/DateInput.tsx
  src/components/ootd/ImageUploader.tsx
  src/components/ootd/LocationInput.tsx
  src/components/ootd/PostInput.tsx
  src/components/ootd/PostOotd.tsx
  src/components/socialLogin/naverLogin.tsx
  src/constants/locations.ts
  src/services/ootd.ts/ootdPost.ts
  src/services/ootd.ts/weather.ts
  src/types/ootd.ts
  yarn.lock
Labels: design, chore, feat

#56 [feat] ootd & 내정보 수정 api
  src/app/mypage/page.tsx
  src/app/onBoarding/page.tsx
  src/app/ootd/[id]/page.tsx
  src/app/ootd/page.tsx
  src/app/page.tsx
  src/components/ootd/DateInput.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/ootd/PostInput.tsx
  src/components/ootd/PostOotd.tsx
  src/components/pages/ootd/RecentOotdPost.tsx
  src/components/pages/ootd/recoootd.tsx
  src/components/profile/MyOotd.tsx
  src/constants/dateFotmat.ts
  src/services/ootd.ts/ootdGet.ts
  src/services/ootd.ts/weather.ts
  src/types/ootd.ts
Labels: fix, design, chore, feat

#59 feat: ootd&내정보 수정 api&회원 탈퇴 api #58
  package-lock.json
  package.json
  public/GoogleLogo.svg
  public/KakaoLogo.svg
  public/icon_comment.svg
  public/icon_heart.svg
  public/icon_pin.png
  src/app/editProfile/page.tsx
  src/components/ootd/CommentSection.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/pages/ootd/RecentOotdPost.tsx
  src/components/profile/EditInfo.tsx
  src/components/userInfo/userModal.tsx
  src/services/auth.ts
  src/services/ootd.ts/ootdComments.ts
  src/services/ootd.ts/ootdGet.ts
  src/store/useUserStore.ts
  src/types/auth.ts
  src/types/ootd.ts
  src/types/react-slick.d.ts
  yarn.lock
Labels: fix, design, chore, feat

#62 feat: 로그인 정보에 따른 팔로우 버튼 렌더링
  src/app/mypage/page.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/profile/MyOotd.tsx
  src/store/useUserStore.ts
Labels: fix, feat

#68 feat: ootd&내정보 수정 api&회원 탈퇴 api
  public/EmptyHeartIcon.svg
  src/components/ootd/CommentSection.tsx
  src/components/ootd/ImageUploader.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/ootd/PostInput.tsx
  src/components/ootd/PostOotd.tsx
  src/components/pages/ootd/RecentOotdPost.tsx
  src/components/profile/EditInfo.tsx
  src/services/ootd.ts/ootdComments.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: fix, design, chore, feat

#73 feat: ootd
  public/arrow_down.svg
  public/arrow_up.svg
  public/dwdwdwd.svg
  public/empty_comment_default.svg
  public/empty_comment_open.svg
  public/empty_heart_default.svg
  public/empty_heart_open.svg
  public/heart_default_empty.svg
  public/heart_empty2.svg
  public/heart_empty_open.png
  public/icon_comment1.svg
  public/icon_down.svg
  public/icon_up.svg
  public/left-arrow.svg
  public/right-arrow.svg
  src/components/ootd/CommentSection.tsx
  src/components/ootd/ImageUploader.tsx
  src/components/ootd/LocationInput.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/ootd/PostOotd.tsx
  src/components/pages/ootd/RecentOotdPost.tsx
  src/components/profile/EditInfo.tsx
  src/components/profile/UserInformation.tsx
  src/constants/dateFotmat.ts
  src/services/ootd.ts/ootdComments.ts
  src/styles/globals.css
Labels: fix, design, chore, feat

#74 feat: ootd
  src/app/mypage/page.tsx
  src/app/user/[id]/page.tsx
  src/components/ootd/CommentSection.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/pages/ootd/RecentOotdPost.tsx
  src/components/profile/MyBadge.tsx
  src/components/profile/MyBookmark.tsx
  src/components/profile/MyOotd.tsx
  src/components/profile/MyTicket.tsx
  src/components/user/userOotd.tsx
  src/components/user/userProfile.tsx
  src/services/ootd.ts/ootdGet.ts
  src/types/ootd.ts
Labels: design, feat

#77 feat: 다른사람 프로필 조회 및 페이지 조회 기능 구현
  src/app/mypage/page.tsx
  src/app/user/[id]/page.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/profile/UserInformation.tsx
  src/components/user/UserBadge.tsx
  src/components/user/UserBookmark.tsx
  src/components/user/UserTicket.tsx
  src/components/user/userOotd.tsx
  src/components/user/userProfile.tsx
  src/types/ootd.ts
Labels: feat

#82 Feature/#55
  package-lock.json
  package.json
  src/app/board/[boardId]/page.tsx
  src/app/oauth/callback/google/page.tsx
  src/app/oauth/callback/kakao/page.tsx
  src/app/ootd/[id]/page.tsx
  src/components/followControl/followButton.tsx
  src/components/ootd/OotdDetail.tsx
  src/components/profile/FollowList.tsx
  src/services/follow.ts
  src/store/useFollowingStore.ts
  yarn.lock
Labels: feat
